version: '3.8'
services:
  bot-gap:
    build: .
    container_name: bot-gap
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
